### ISSUE TITLE
Lost connection to backend error

### ISSUE THREAD

**Issue by manniebugs** [SecurityPhoton/scanner#1]
Hey,

I was using your project and have been seeing an error "Connection to the backend is lost. Please check your network." even though the backend is working fine.

Here my compose config:
```
services:
  scanner:
    image: ghcr.io/securityphoton/nmap-gui:latest
    container_name: scanner
    ports:
      - 8080:80/tcp
      - 8081:8000/tcp
    restart: unless-stopped
```

Here's a screenshot of the error
![screenshot](https://github.com/user-attachments/assets/b733d95a-c671-4ef0-b137-48e8c59c7cd4)

I was able resolve the issue by changing the following line from `/api/health-check` to `/health-check`
https://github.com/SecurityPhoton/scanner/blob/50c538a91c2568a6e4ddc83717bb2b8c392cf30e/backend/main.py#L28

Nice tool you made, it's come in handy a few times.
